### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by bad989** [msxmine/SI2DSU#2]
(if it gets hard to understand i'm sorry i'm brazilian and i'm using google translator) 
![Capturar](https://user-images.githubusercontent.com/43222642/110173368-3d9ee500-7ddd-11eb-8c08-23a0cc508d97.PNG)
I did everything I asked I put the configuration file in the steam folder, I created a "dsu" folder and I put all the game files, I pasted the program and renamed the .exe, I put the shortcut in Steam I defined in the startup "-dsumode" and I did the same with the cemu roms shortcuts and when I open the program it doesn't work and it only works if I opened the steam game executable with "-dsumode" but then only opens the program

**Comment by msxmine** [comment]
So it works and starts cemu only if you launch the original game (Vanquish), from steam with (-dsumode) ? Does it pass the extra arguments to cemu? Will starting Vanquish with (-dsumode -f -g "C:\Path\To\WiiU\Games\RedCarpet.rpx") start 3d world? Your dsusettings.txt file needs to have the path to cemu in the first line, the number 460810 in the second line.

**Comment by msxmine** [comment]
Also to create game shortcuts, I assume you add the vanquish.exe (di2dsu.exe) as a non-steam game? First remove all arguments (-dsumode) from the original vanquish entry on steam. Only set the arguments on the shortcuts. Also, now that I think about it, maybe try moving the entire vanquish install to a steam library somewhere else than C:\Program Files. SI2DSU briefly creates dsuparams.txt in its directory, and Windows may need admin permissions to create files in C:\Program Files. If that works, I will update SI2DSU to create the file in some public user temp directory

**Comment by bad989** [comment]
> Então funciona e inicia cemu apenas se você lançar o jogo original (Vanquish), do Steam com (-dsumode)? Isso passa os argumentos extras para cemu? Iniciar o Vanquish com (-dsumode -f -g "C: \ Path \ To \ WiiU \ Games \ RedCarpet.rpx") iniciará o mundo 3D? Seu arquivo dsusettings.txt precisa ter o caminho para cemu na primeira linha, o número 460810 na segunda linha.

opens the original game (Vanquish) starts the argument (-dsumode) but there is no way to configure the control as it does not open a game screen, running the original steam game (-dsumode -f -g "C: \ Path \ To \ WiiU \ Games \ RedCarpet.rpx") just runs the argument (-dsumode), my file (dsusettings.txt) is already with Cemu's location and is with Vanquish's id
![Capturar](https://user-images.githubusercontent.com/43222642/110211915-9b800b00-7e77-11eb-8ec4-2f662e52f925.PNG)

**Comment by bad989** [comment]
> Além disso, para criar atalhos de jogo, suponho que você adicione o vanquish.exe (di2dsu.exe) como um jogo não Steam. Primeiro remova todos os argumentos (-dsumode) da entrada vanquish original no Steam. Defina apenas os argumentos nos atalhos. Além disso, agora que pensei sobre isso, talvez tente mover toda a instalação do vanquish para uma biblioteca do Steam em algum lugar diferente de C: \ Arquivos de Programas. O SI2DSU cria rapidamente dsuparams.txt em seu diretório e o Windows pode precisar de permissões de administrador para criar arquivos em C: \ Arquivos de programas. Se funcionar, atualizarei o SI2DSU para criar o arquivo em algum diretório temporário de usuário público



> vanquish

vanquish is installed on the drive (D :)

**Comment by bad989** [comment]
is the program having problems because of the several HDD units I have? since the original steam game is on D: the emulator on E: and the ROM on F:?

**Comment by msxmine** [comment]
> 
> 
> is the program having problems because of the several HDD units I have? since the original steam game is on D: the emulator on E: and the ROM on F:?

It shouldn't matter. If anything, the problem may be the spaces in folder names. I'm working on a new version to help with debugging

**Comment by msxmine** [comment]
Please try this version
[sidsu.zip](https://github.com/msxmine/SI2DSU/files/6096437/sidsu.zip)

**Comment by bad989** [comment]
> Por favor, tente esta versão
> [sidsu.zip](https://github.com/msxmine/SI2DSU/files/6096437/sidsu.zip)

now it's working
![Capturar](https://user-images.githubusercontent.com/43222642/110245459-f54d0780-7f41-11eb-93fa-27e25d6956db.PNG)

**Comment by bad989** [comment]
and Citra? can i put the citra directory in .txt and can i open a game the same way? without replacing Cemu

**Comment by bad989** [comment]
and dualshock 4 touchpad how to configure?

**Comment by msxmine** [comment]
> 
> 
> in the citra only the motion sensor works, the touchpad does not respond and the citra does not support the "dsuclient" to configure the control so I changed it myself. can you fix at least the touchpad?
> ![Capturar2](https://user-images.githubusercontent.com/43222642/110247072-0a796480-7f49-11eb-8bab-466ba380b937.PNG)

In this steam configuration screen, you need to remap everything to the actions from the game_actions_id.vdf file for the buttons and joysticks to work. The default steam actions for Xinput won't do anything. Unfortunatelly having good defaults is only documented for games published on steam, so in this case the user has to create good configuration himself after install. Try remapping any button, and you should see the actions from the file to choose from. For example "Left Joystick Press" or "D-Pad Right". Just map everything to the corresponding buttons. 

As for the DS4 touchpad, I will try to add something, but SteamInput is somewhat limited.

**Comment by msxmine** [comment]
I made a new version.
Now, to use multiple emulators you don't need multiple steam games. You can override the exe file path from dsusettings.txt with an argument like this (-dsumode -dsuclientexe "C:\path\to\Cemu.exe" -f -g "D:\path\to\game.rpx") 
Also, there are now actions to bind to the touchpad. (So replace the game_actions.vdf file with the new version) I'm not sure if they will work, but you should be able to set the touchpad as a joystick in steam overlay and bind it to "TouchPad XY Input". You also need to go into the advanced binding options and bind touching the touchpad to "TouchPad Touch" and the touchpad button to "TouchPad Press"

This version is not built in debug mode, so the black terminal window will not show up.

[v2.zip](https://github.com/msxmine/SI2DSU/files/6097973/v2.zip)

**Comment by msxmine** [comment]
Worst case, if the touchpad still doesn't work, you should be able to use steam's built-in feature to bind it to the mouse pointer. The "Mouse Region" or "Absolute Mouse" input source modes should work fine for that.

**Comment by bad989** [comment]
> Na pior das hipóteses, se o touchpad ainda não funcionar, você deve ser capaz de usar o recurso embutido do Steam para ligá-lo ao ponteiro do mouse. Os modos de fonte de entrada "Região do mouse" ou "Mouse absoluto" devem funcionar bem para isso.

the control does not respond in the emulator with this new version

**Comment by msxmine** [comment]
[v3.zip](https://github.com/msxmine/SI2DSU/files/6098021/v3.zip)

Does this work?

**Comment by bad989** [comment]
> [v3.zip](https://github.com/msxmine/SI2DSU/files/6098021/v3.zip)
> 
> Isto funciona?

it returned to work and the touchpad is also working but there is another problem Citra is calibrating wrong giving x0 y0 value and citra only recognizes the input if it is put in the steam "touchpad touch" and I have to press instead of touching
![Capturar5](https://user-images.githubusercontent.com/43222642/110256526-29431f80-7f78-11eb-94dc-5984e3573c05.PNG)

**Comment by msxmine** [comment]
According to this: https://partner.steamgames.com/doc/features/steam_controller/input_source_modes (Under Joystick Move), there is a separate binding for press (Click Action), and a separate binding for touch (Touch binding) hidden under Additional Settings.

As for the calibration, I don't really know what the values should be. I assumed that (960,471) is center, because I found those values in the DS4 HID report specs. If you know the real ranges for X and Y in DSU that's great

**Comment by bad989** [comment]
> De acordo com isso: https://partner.steamgames.com/doc/features/steam_controller/input_source_modes (em Joystick Move), há uma ligação separada para pressionar (ação de clique) e uma ligação separada para toque (ligação por toque) oculta em Configurações adicionais.
> 
> Quanto à calibração, não sei realmente quais devem ser os valores. Presumi que (960.471) é o centro, porque encontrei esses valores nas especificações do relatório DS4 HID. Se você conhece os intervalos reais de X e Y no DSU, isso é ótimo


using Ryochan7's other "ds4Windows" software works normal
![Capturar6](https://user-images.githubusercontent.com/43222642/110257005-a8395780-7f7a-11eb-8e73-850624c9f087.PNG)
I don't know if it can help, but here is the right value of the calibration

**Comment by bad989** [comment]
it would be great to see your program together with ds4windows, both have great ideas

**Comment by msxmine** [comment]
So the ranges of X(0-1919) and Y(0-942) seem fine. What is the issue?

**Comment by bad989** [comment]
> Portanto, os intervalos de X (0-1919) e Y (0-942) parecem bons. Qual é o problema?

only works with ds4windows and if ds4windows is running steam input does not work

**Comment by msxmine** [comment]
I understand, but how exactly does the touchpad not work? It clearly sends something, as otherwise Citra wouldn't show the ranges. Are the X Y values fine in the DSU Controller Test program when pressing the touchpad?

**Comment by bad989** [comment]
> Eu entendo, mas como exatamente o touchpad não funciona? Ele claramente envia algo, caso contrário, o Citra não mostraria os intervalos. Os valores XY são bons no programa de teste do controlador DSU ao pressionar o touchpad?

with dsumode the touchpad responds but with X and Y 0 then it doesn't matter where I click on the touch

**Comment by msxmine** [comment]
[sidsu.zip](https://github.com/msxmine/SI2DSU/files/6098108/sidsu.zip)
Does this one show anything when you use the pad?

**Comment by bad989** [comment]
> [sidsu.zip](https://github.com/msxmine/SI2DSU/files/6098108/sidsu.zip)
> Este mostra alguma coisa quando você usa o teclado?

ah? I didn't understand do you want me to use the keyboard?

**Comment by msxmine** [comment]
No. This version shoud show some information in a black terminal window, about the detected X Y position on the DS4 touchpad

**Comment by bad989** [comment]
udp server is not responding


> Não. Esta versão deve mostrar algumas informações em uma janela de terminal preta, sobre a posição XY detectada no touchpad DS4

udp server is not responding

**Comment by bad989** [comment]
> [sidsu.zip](https://github.com/msxmine/SI2DSU/files/6098108/sidsu.zip)
> Este mostra alguma coisa quando você usa o teclado?

google translator exchanged "pad" for keyboard kkkkkkkk

**Comment by msxmine** [comment]
> 
> 
> > Não. Esta versão deve mostrar algumas informações em uma janela de terminal preta, sobre a posição XY detectada no touchpad DS4
> 
> udp server is not responding

Weird. How about this one ?

[sidsu.zip](https://github.com/msxmine/SI2DSU/files/6098122/sidsu.zip)

**Comment by bad989** [comment]
> > > Não. Esta versão deve mostrar algumas informações em uma janela de terminal preta, sobre a posição XY detectada no touchpad DS4
> > 
> > 
> > o servidor udp não está respondendo
> 
> Esquisito. Que tal este ?
> 
> [sidsu.zip](https://github.com/msxmine/SI2DSU/files/6098122/sidsu.zip)

Matrix?
![Capturar](https://user-images.githubusercontent.com/43222642/110258494-9e672280-7f81-11eb-9807-cbde4bd197ec.PNG)

**Comment by msxmine** [comment]
Ok. I was trying to add handling for when there are no controllers connected, but it clearly messes something up and steam doesn't seem to mind being asked about the buttons, even if nothing is connected, so I will let it be like this. 
So on your screenshot, it looks like the touchpad is ok? What do the Xreal and Yreal values say when you are not touching it? Does "TP now" change to true when you are touching it? Is Xreal and Yreal = -1 in the upper left corner and 1 in the lower right?

**Comment by bad989** [comment]
no upper left corner Xreal -1 YReal 1. bottom right corner Xreal 1 YReal -1

**Comment by msxmine** [comment]
Does it work at all? Maybe the Y axis is reversed?

**Comment by bad989** [comment]
> Funciona mesmo? Talvez o eixo Y esteja invertido?

the touchpad responds normal. the emulator that doesn't respond right
![Capturar](https://user-images.githubusercontent.com/43222642/110259779-38ca6480-7f88-11eb-80af-1d6b1cd597cb.PNG)

**Comment by msxmine** [comment]
Have you tried pressing all the corners to see if something happens? Or even pressing near the center? See what DSU controller test reports on each corner and compare to what it reports with ds4windows. Maybe the axis are flipped, or maybe steam maps the joystick near the center, or maybe the values must be >0 for it to work and I shoud clamp them to at least 1.

**Comment by msxmine** [comment]
In DSU controller test, touchpad reading is T0 and Tracked0 I think

**Comment by bad989** [comment]
> Você já tentou pressionar todos os cantos para ver se algo acontece? Ou mesmo pressionando perto do centro? Veja o que o teste do controlador DSU reporta em cada canto e compare com o que reporta com ds4windows. Talvez o eixo esteja invertido ou talvez mapeie o joystick próximo ao centro, ou talvez os valores devam ser> 0 para que funcione e eu devo fixá-los em pelo menos 1.

I pressed it in several different places and so from time to time the game happens something but like I click in the middle of the touchpad in the game it responds as if I had pressing in the bottom left corner. it's pretty random

**Comment by msxmine** [comment]
For reference the Xreal and Yreal values are what steam sends and are in range (-1 to 1) and Xdsu and Ydsu are what I send and are in range (0 to 1919 for X and 0 to 471 for Y). I don't know if positive is up or down, so you should compare to ds4windows in the DSU controller test program to see if something isn't reversed. Also just try sliding the finger around and looking at the Xreal and Yreal values. It's possible that steam creates a virtual joystick somewhere in the middle of the touchpad and doesn't send the real values for the whole rectangle, just a small circle. In that case, I can't do anything. Steam doesn't share the raw touchpad data. There is only joystick mode and mouse mode. In mouse mode it sends the deltas (changes) so it's useless.

**Comment by bad989** [comment]
> Para referência, os valores Xreal e Yreal são o que o Steam envia e estão no intervalo (-1 a 1) e Xdsu e Ydsu são o que eu envio e estão no intervalo (0 a 1919 para X e 0 a 471 para Y). Não sei se positivo é para cima ou para baixo, então você deve comparar com ds4windows no programa de teste do controlador DSU para ver se algo não está revertido. Experimente também deslizar o dedo e observar os valores Xreal e Yreal. É possível que o Steam crie um joystick virtual em algum lugar no meio do touchpad e não envie os valores reais para todo o retângulo, apenas um pequeno círculo. Nesse caso, não posso fazer nada. O Steam não compartilha os dados brutos do touchpad. Existe apenas o modo joystick e o modo mouse. No modo mouse, ele envia os deltas (alterações), portanto, é inútil.

wait for what I understood each point of the touchpad has an X and Y value (-1,-0,0,1) and this each coordinate was a button? example (x-1 y1 = K on the keyboard) in citra has the ability to map buttons on the touch

**Comment by bad989** [comment]
I tried to hear the windows sound of something stopped working
![Capturar3](https://user-images.githubusercontent.com/43222642/110261922-c316c680-7f90-11eb-8d2a-61b125fecbdd.PNG)

**Comment by bad989** [comment]
> Para referência, os valores Xreal e Yreal são o que o Steam envia e estão no intervalo (-1 a 1) e Xdsu e Ydsu são o que eu envio e estão no intervalo (0 a 1919 para X e 0 a 471 para Y). Não sei se positivo é para cima ou para baixo, então você deve comparar com ds4windows no programa de teste do controlador DSU para ver se algo não está revertido. Experimente também deslizar o dedo e observar os valores Xreal e Yreal. É possível que o Steam crie um joystick virtual em algum lugar no meio do touchpad e não envie os valores reais para todo o retângulo, apenas um pequeno círculo. Nesse caso, não posso fazer nada. O Steam não compartilha os dados brutos do touchpad. Existe apenas o modo joystick e o modo mouse. No modo mouse, ele envia os deltas (alterações), portanto, é inútil.

nothing is inverted. I did a little demonstration of how X and Y are doing
![335834b5fb0892a78b9e827251a75414](https://user-images.githubusercontent.com/43222642/110262233-cfe7ea00-7f91-11eb-993c-955ecd0d3778.jpg)
